server.port=3001
spring.application.name=upload-service
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
file.upload-dir=c:/Users/prash/Desktop/dynatrace_poc2/uploads
